SELECT 
    A.ID,
    A.FISH_NAME,
    A.LENGTH 
FROM (
    SELECT 
        RANK() OVER(PARTITION BY F.FISH_TYPE ORDER BY F.LENGTH DESC) AS NUM,
        I.FISH_NAME,
        F.LENGTH,
        F.ID
    FROM FISH_INFO F
    JOIN FISH_NAME_INFO I ON I.FISH_TYPE = F.FISH_TYPE
)A
WHERE A.NUM = 1
ORDER BY A.ID
